Repository recc-tech/tech, pull requests merged in 2025-06, with the labels that each got.

#620 Fix bug in locating kids video
  scripts/config/config.toml
  scripts/lib/assets.py
  scripts/test/integration/test_download_assets.py
Labels: bug

#622 Update checklists and tasks
  README.md
  checklists/weekly/foh-video-setup.md
  checklists/weekly/mcr-sound-setup.md
  checklists/weekly/mcr-video-setup.md
  scripts/config/mcr_setup_tasks.json
  scripts/config/mcr_teardown_tasks.json
  scripts/setup/set-up-dev-env.sh
  scripts/summarize_plan.py
Labels: documentation

#627 Update kids video regex (again)
  scripts/config/config.toml
  scripts/test/unit/test_download_pco_assets.py
Labels: bug

#632 Fix --dry-run in download_pco_assets.py
  scripts/download_pco_assets.py
Labels: bug

#637 Generate summary of visuals notes
  scripts/config/config.toml
  scripts/config/src/config.py
  scripts/lib/__init__.py
  scripts/lib/summarize_plan.py
  scripts/summarize_vocals_notes.bat
  scripts/summarize_vocals_notes.command
  scripts/summarize_vocals_notes.py
  scripts/test/integration/summarize_plan_data/20240505_vocals_notes.json
  scripts/test/integration/test_summarize_plan.py
Labels: enhancement
